# Generated by Django 4.2.1 on 2023-06-07 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_tags_alter_tag_name_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, to='blog.tag'),
        ),
    ]
